### ISSUE TITLE
Container not found

### ISSUE THREAD

**Issue by carolindahms** [ncbi/fcs#103]
Hi,
When I run the latest FCS adaptor, I keep getting the error `Error response from daemon: No such container: run_av_screen_x `
I ran: ./run_fcsadaptor.sh --fasta-input myfasta.fa --output-dir ./FCS/ --euk

My Docker version is 24.0.7, build 24.0.7-0ubuntu2~20.04.1:

```
0.5.4: Pulling from ncbi/fcs-adaptor
Digest: sha256:96a5609b4a8eb847577a2a3971c5f743349dd53fb53d39c65793eb3f1e6fe49b
Status: Image is up to date for ncbi/fcs-adaptor:0.5.4
docker.io/ncbi/fcs-adaptor:0.5.4
Resolved '/app/fcs/progs/ForeignContaminationScreening.cwl' to 'file:///app/fcs/progs/ForeignContaminationScreening.cwl'

```
I saw there was a similar issue before ( #10 ), I wonder how it got fixed?

Thank you for any help!
Carolin

**Comment by etvedte** [comment]
Hi Carolin,

I don't see a specific connection to the other issue you posted.

However we have seen `Error response from daemon: No such container: run_av_screen_x` messages before. Do you see output from this run? i.e. , what are the contents of `./FCS/`?

Eric

**Comment by carolindahms** [comment]
Hi Eric,
thank you so much for getting back so quickly.
I had the same warning message before ```
 [WARN  tini (8)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
```
as in issue #10, thought that was maybe related, so I added the -s option in the script (and now I'm not getting that Tini warning again).

the outputs are  a cleaned_sequences folder with my input file, some logs and some empty report txts, I have attached the folder here if that helps:
[archive.zip](https://github.com/user-attachments/files/17928424/archive.zip)

Thanks for any help!

Carolin

**Comment by etvedte** [comment]
We can see about a fix for `No such container:` warning.

When we saw this previously, it didn't seem to affect the output. Your `fcs_adaptor.log` looks like the pipeline completed successfully.

Could you please run through the [example](https://github.com/ncbi/fcs/wiki/FCS-adaptor-quickstart#usage-examples) from the quickstart and see if the results match the expected output? If so, then I would be confident about the empty adaptor report from your run reflecting that FCS-adaptor did not identify any contamination from adaptors.
