### ISSUE TITLE
fcs-adapter: failure at blast stage 

### ISSUE THREAD

**Issue by cahende** [ncbi/fcs#11]
Everything seems to run well until I get to the blast component of the process and something called "permanentFail" happens. See the related portion of the output.

`[job blast] /tmp/t3in7b64$ vecscreen \
    -db \
    adaptors_for_euks \
    -logfile \
    vecscreen.log \
    -out \
    vs_unfiltered.hit \
    -query \
    /tmp/xuzc6dak/stg4422339b-1c5a-4825-b5cf-fa3149a30819/split_fasta.fna
[job blast] Max memory used: 54MiB
[job blast] completed permanentFail
[step blast] completed permanentFail
[workflow AdaptorScreeningAndFilterResults] completed permanentFail
[step AdaptorScreeningAndFilterResults] completed permanentFail
[workflow parallel_section] completed permanentFail
[step parallel_section] completed permanentFail
[workflow ] completed permanentFail
Output will be placed in: /output-volume
Executing the workflow
Completed permanentFail
run_av_screen_x
run_av_screen_x
`

**Comment by pstrope** [comment]
Hi, 
Did the commands with the example file (as listed in the docs) work for you?
Is there something different with the fasta file (eg. header line, or sequences)?

**Comment by cahende** [comment]
Nothing unique about the fasta file as far as I know. They were processed
appropriately when submitted to GenBank, but the internal adapters weren't
automatically removed so I need to do that manually. I used the commands
here https://github.com/ncbi/fcs/wiki/FCS-adaptor.

Cory

**Comment by deaconjs** [comment]
Hi Cory, 

Thanks for bearing with us as we work through some growing pains!

Our next release will include a debug mode for adaptor. For now you can trigger debug mode with a slight change to the caller script, run_fcsadaptor.sh. Please change line 113 in the script from:
**/app/fcs/bin/av_screen_x -o /output-volume/ $TAX /sample-volume/$FASTA_FILENAME**
to:
**/app/fcs/bin/av_screen_x -o /output-volume/ --debug $TAX /sample-volume/$FASTA_FILENAME**
to create verbose debug output. 

A subfolder in your output folder will be created, called debug.########/ (some random token is at the end. Within that subfolder are tmp-outdir########_fast_split.log and tmp-outdir########_vecscreen.log. These are normally filled with simple start, extra, and stop output, but should have some error messaging for your case. Please post the content of those files here and we will review.

Thank you,
Deacon

**Comment by etvedte** [comment]
Closing. Please follow-up if you have other questions.
