### ISSUE TITLE
Avoid using /tmp

### ISSUE THREAD

**Issue by tk2** [ncbi/fcs#15]
Hi - thanks for posting the container version of the contamination screening tool. I'm trying out the run_fcsadaptor.sh and it runs just fine on the test data version via singularity. When I try to scale up to a eukaryote genome, I get an error about running out of space in /tmp. Is there any way to provide an alternative temp directory? I can see that a working directory is established in /tmp for the ValidateInputSequences step. The bash script doesn't have an option to provide an alternative working directory.

**Comment by victzh** [comment]
Thank you for your interest in our products!

Can you try setting TMPDIR environment variable to a directory with more space? As far as I can tell we don't use /tmp explicitly, but mktemp which is called in the validation step should honor TMPDIR.

**Comment by tk2** [comment]
Thanks for the clarification, setting TMPDIR seems to have addressed the issue. Now up and running on the larger genome.
