### ISSUE TITLE
The result file is missing an important column

### ISSUE THREAD

**Issue by abcyulongwang** [ncbi/fcs#16]
Hi,Thank you very much for designing this software！
 
I encountered such an error when running the software.

![image](https://user-images.githubusercontent.com/93254434/197395443-f8975cfc-0ec3-4089-aa22-cb69766528c4.png)

But surprisingly, the result file still outputs the  .prt.tmp  file. But when I view the result file, I find that the result file lacks several key columns. such as "weight" "result" "div " "div_pct_cvg ". This makes it impossible for me to accurately determine the type of species to which the sequence belongs only through the information of "div-1", "div-2", "div-3" and "div-4"

![image](https://user-images.githubusercontent.com/93254434/197395863-b461ddaf-15fe-4fb2-8697-501edb1ebc0d.png)

At present, I have no good way to solve this problem, and I really hope to get your help!

Best
yulong

**Comment by pstrope** [comment]
Hi Yulong,

Please try again with the most recent run script.
```curl -LO https://github.com/ncbi/fcs/raw/main/dist/run_fcsgx.py```
The latest docker image should be v0.2.3

If you still encounter an error, please paste a complete log.

The rpt.tmp file that you posted is a transient intermediate file and looks as expected but is different from the actual result output file. 

Thank you for your feedback, and let us know how it goes. 

Pooja

**Comment by abcyulongwang** [comment]
Thanks for your reply, I have successfully solved the problem.

Good luck！
