### ISSUE TITLE
Pre download for the FCS-GX database

### ISSUE THREAD

**Issue by tillenglert** [ncbi/fcs#18]
Hi,

I was wondering if you can specify the location of the full and test database or specify a path where I can manually download the files? We need to pre download larger files, as automatic downloads are not permitted on our cluster and we would also like to include a test without downloading both databases first.

Thank you in advance and all the best,

Till

**Comment by tillenglert** [comment]
I found the ftp page, which can solve our problems! Thanks anyway!

**Comment by lstxmu** [comment]
Hi，tillenglert
Can you show me the ftp page of FCS-GX datebse ?  
Thanks for your help

**Comment by tillenglert** [comment]
Hi Istxmu,

I found the databases digging through the docker container:

https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/FCS/database/

Hope it helps!
