### ISSUE TITLE
St13runtime_error in 'all' test 

### ISSUE THREAD

**Issue by bibionid** [ncbi/fcs#24]
Hello, 

Thank you very much for your work on what seems to be a very exciting tool. 

I'm currently trying to get a local version to work on our HPC. I have downloaded the all database and copied it to shm. 

run_gx is starting, but fails after minutes with the attached error. 

I would be most grateful if you could offer any insight? 

Thanks in advance!

Command 
```
srun run_fcsgx.py \
  --fasta ./testing/fcsgx_test.fa.gz\
  --out-dir ./gx_out/ \
  --container-db "${SHM_LOC}/gxdb/" \
  --gx-db "${SHM_LOC}/gxdb/all" \
  --split-fasta \
  --tax-id 6973 \
  --debug
```

[xy_fcs_52030726_n83032.err.txt](https://github.com/ncbi/fcs/files/10133787/xy_fcs_52030726_n83032.err.txt)
[xy_fcs_52030726_n83032.out.txt](https://github.com/ncbi/fcs/files/10133788/xy_fcs_52030726_n83032.out.txt)

**Comment by pstrope** [comment]
Hi,
Are you using the most recent version of the Singularity/Docker image and run_fcsgx.py?

Is there by any chance empty (defline-only) sequences in your input?

**Comment by bibionid** [comment]
Hello, 

Thank you very much for the swift response!

I am using the most recent of both singulaity container and run_fcsgx.py

The input is unchanged from the examples dir in this repo

**Comment by bibionid** [comment]
Sorry, I hadn't noticed you had realsed this -  I will get it installed and see if it solves the issue.

**Comment by pstrope** [comment]
Closing. Please follow-up if you have other questions.
