### ISSUE TITLE
[BUG]: using manifest file requires gzipped input

### ISSUE THREAD

**Issue by ptrebert** [ncbi/fcs#32]
*Describe the bug*
If the input is provided as manifest file, then the execution fails
```
gzip: /PATH-TO-FASTA/assembly.unassigned.fasta.gz: No such file or directory
Error: Process failed with retcode 123: ['xargs', '-n1', 'gzip', '-cdf'])
```
because the file extension `.gz` is silently appended to the file name. Gzipping the individual files listed in the manifest then works.

*To Reproduce*
Prepare manifest file with uncompressed input (file extension `.fasta` in the above case)

*Software versions (please complete the following information):*
 See #31 

*Log Files*
not needed

*Additional context*
**Remark**: in case a manifest file is only recognized on the basis of the file extension `.mft` (this is given in the usage examples in the wiki), it should be explicitly documented in the wiki. I haven't tested the behavior explicitly.

Best,
Peter

**Comment by pstrope** [comment]
Hi Peter,
Regarding the manifest file:
- the option was only introduced to support our submission screening process, and given the added complexity necessary for supporting the path mapping needed with containers we're removing support for the option at this time.

Thank you for your feedback!

Pooja

**Comment by ptrebert** [comment]
I see, too bad that option will be removed. Thanks for letting me know.
