### ISSUE TITLE
[BUG]: run_fcsgx.py fails if out dir is not present

### ISSUE THREAD

**Issue by ptrebert** [ncbi/fcs#33]
*Describe the bug*
`run_fcsgx.py` fails if the output directory is not present.

*To Reproduce*
Start the tool w/o creating the directory first.

*Software versions (please complete the following information):*
See #31 

*Log Files*
not needed

*Additional context*
This might arguably be more of a feature request, and I have seen that your tutorial is complete in that regard

```
6. Create a directory to store the output of the program:
```
So here is just my view:
- `run_fcsgx.py` is a nice Python wrapper with a clean interface, so it would be trivial to add this check before calling `RunGX()`
  - What happens if the directory contains files from a previous (failed) run? Is the run continued, or does it start from scratch in any case? 
- The current implementation requires all users to attentively read the complete tutorial; I know, we all would like our users to do this, but in reality ... it would avoid some frustration / improve usability.
- If the FCS is integrated into a larger workflow, it depends on the workflow manager if the output dir is created or not before a command is executed. In other words, it's again on the user to remember to always call a `mkdir` first if necessary.

Best,
Peter

**Comment by pstrope** [comment]
In the new version that we are going to release soon, the output dir will be created if not already present. Re-running the program will start the screening process from the beginning. The files will be re-written. 

Thank you so much for your comments and suggestions!
