### ISSUE TITLE
[BUG]: Assertion failed: seen_queries.insert(next_seq_id).second

### ISSUE THREAD

**Issue by ptrebert** [ncbi/fcs#34]
*Describe the bug*
`run_fcsgx.py` fails with the above message; I strongly assume that this is triggered if two sequences in the FASTA files have the same name.

*To Reproduce*
Use same sequence names more than once in different input files.

*Software versions (please complete the following information):*
See #31 

*Log Files*
Not needed.

*Additional context*
This was triggered when using a manifest listing several FASTA files as input for a single run. Obviously, a name clash can be expected if several input datasets are created in the same way (here: same assembler following a single naming scheme).

A user-friendly solution would be to introduce another command line parameter that allows to supply a list of sample labels that are used in addition to the FASTA header to identify a sequence. I guess this would require more work on the internals of the FCS tools, so it should at least be made explicit in the wiki where the possibility of using a manifest file is explained.

Best,
Peter

**Comment by pstrope** [comment]
Regarding the manifest file:
- the manifest option is only intended for a single genome in multiple files
- the option was only introduced to support our submission screening process, and given the added complexity necessary for supporting the path mapping needed with containers we're removing support for the option at this time.

There will be a new version release soon.

thanks!
