### ISSUE TITLE
clean genome with singularity

### ISSUE THREAD

**Issue by scorreard** [ncbi/fcs#37]
Hi team,

I run fcs-gx with singularity using the following command (which works very well)
```
python3 /app/bin/run_gx \\
        --fasta $assembly \\
        --out-dir . \\
        --gx-db ${params.fcs_gx_database} \\
        --tax-id ${params.taxon_taxid} \\
        $args
```

I would like to now run the new option 'E. Remove the contaminant sequences'
However, I can't find the equivalent command for clean genome.

When I use the python file, I have an error

Code :
```
singularity exec -B /Arctic_surfclam_005/V1/work -e -W //tmp/ -B /projects,/home /singularity/ftp.ncbi.nlm.nih.gov-genomes-TOOLS-FCS-releases-0.4.0-fcs-gx.sif /bin/bash

> zcat Arctic_surfclam_005.cleaned_sequences.fa.gz | python3 /singularity//fcs.py clean genome --action-report Arctic_surfclam_005.cleaned_sequences.fa.31204.fcs_gx_report.txt --output cleaned.fasta --contam-fasta-out contam.fasta
```

Error : 
```
Traceback (most recent call last):
  File "/singularity/fcs.py", line 480, in <module>
    sys.exit(main())
  File "/singularity//fcs.py", line 469, in main
    gx.run()
  File "/singularity//fcs.py", line 386, in run
    self.args.func(self)
  File "/singularity//fcs.py", line 382, in run_clean_mode
    self.run_gx()
  File "/singularity//fcs.py", line 235, in run_gx
    self.safe_exec(docker_args)
  File "/singularity//fcs.py", line 150, in safe_exec
    subprocess.run(args, shell=False, check=True, text=True, stdout=sys.stdout, stderr=sys.stderr)
  File "/miniconda3/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/miniconda3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/miniconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker': 'docker'
```

*Software versions :*
- Local HPC
-  singularity version 3.5.2-1.1.el7
 - Docker or Singularity FCS image version  : ftp.ncbi.nlm.nih.gov-genomes-TOOLS-FCS-releases-0.4.0-fcs-gx.sif
 - Python version if using FCS-GX Python 3.7.8
 

Thanks for your work and the update, looking forward being able to clean the genome without a third party

**Comment by pstrope** [comment]
It looks like you are trying to run fcs.py (the wrapper script that prepares and executes docker or singularity command) from within a shell executing within Singularity container. Instead, please try running your command as follows (outside of container):
`zcat Arctic_surfclam_005.cleaned_sequences.fa.gz | python3 /singularity/fcs.py --image=/singularity/ftp.ncbi.nlm.nih.gov-genomes-TOOLS-FCS-releases-0.4.0-fcs-gx.sif clean genome --action-report=Arctic_surfclam_005.cleaned_sequences.fa.31204.fcs_gx_report.txt --output=cleaned.fasta --contam-fasta-out=contam.fasta`

**Comment by scorreard** [comment]
It works!

Thank you very much for the quick and efficient answer!
