### ISSUE TITLE
How to create custom DataBase for FCS-GX?

### ISSUE THREAD

**Issue by maruiqi0710** [ncbi/fcs#40]
I want to set the mtDNA of a certain species as a database, and use FCS-GX tool to remove mtDNA from the (nuclear DNA) genome assembly of that species.

**Comment by pstrope** [comment]
Hi, 
We currently do not have any plans to add a feature for creating custom databases. Identification of non-contaminant organelle sequences is something we’re considering for the future, but isn’t currently implemented. 
For your genome assembly, running blast against the mtDNA sequences might get you to the desired result.
