### ISSUE TITLE
Are endogenous elements removed by FCS? 

### ISSUE THREAD

**Issue by BenjaminGuinet** [ncbi/fcs#41]
Dear Foreign Contamination Screen developers.

In submitting sequences to Genbank as genome assemblies, I was wondering if FCS actually considers endogenous viral elements as contaminating sequences to be removed from the assembly?

Thank you very much for your time.

All the best,

Benjamin

**Comment by etvedte** [comment]
Is this the complete contig sequence? Can you post the row(s) for the action report (*fcs_gx_report.txt) and the taxonomy report (*taxonomy.rpt) for this contig?

**Comment by BenjaminGuinet** [comment]
Yes sure.

It is the complete contig and here is the raw from the report : 

```
Exclude:
Sequence name, length, apparent source
scaffold18160	4420	virs:viruses

```

**Comment by murphyte** [comment]
FYI, our submitted paper is available on BioRxiv: https://biorxiv.org/cgi/content/short/2023.06.02.543519v1

I'll send you the report later today.
