### ISSUE TITLE
[DOC SUGGESTION]: Not clear what `cleaned_sequences` is in FCS tool

### ISSUE THREAD

**Issue by conchoecia** [ncbi/fcs#46]
Thanks for putting this tool online! It's nice to be able to fix our genomes before uploading them to NCBI and catching the problems then.

I ran the FCS adapter tool (`run_fcsadaptor.sh`) on a genome and got plenty of adapters to trim out. I then noticed the `cleaned_sequences` directory and saw that there is a copy of the genome there. This genome, however, doesn't have the adapter sequences replaced with Ns (I think this should be the default behavior), and when I faidx out the regions that are listed in the contamination report I find that there are still PacBio Blunt Adapter sequences still there:

TATCTCTCTCTTTTCCTCCTCCTCCGTTGTTGTTGTAGAGAGAGATACAGTC

So I'm wondering what is being done to the fasta file in `cleaned_sequences`? For now I think I will just trim the genome with a custom script.

**Comment by etvedte** [comment]
Hello,

> This genome, however, doesn't have the adapter sequences replaced with Ns...when I faidx out the regions that are listed in the contamination report I find that there are still PacBio Blunt Adapter sequences still there 

From this description I am guessing that the PacBio adaptor hits are internal contig hits and not near contig ends, else they should have been removed automatically. The contamination report should have sequences labeled ACTION_TRIM (not ACTION_EXCLUDE). Is this correct? See: https://github.com/ncbi/fcs/wiki/FCS-adaptor#rules-for-action-assignment

> I think this should be the default behavior

We have received feedback about masking and hope to incorporate it into a future release (See: https://github.com/ncbi/fcs/wiki/FCS-adaptor#known-issues-and-future-improvements). One potential issue with setting hardmask as default is that contigs joined by an adaptor could be a false contig join and it would be better to split into two separate contigs. We do appreciate this feedback and can follow up when this feature is added.

Are there a lot of hits in the contamination report? If so, may want to consider a read adaptor trimming tool then re-assemble. If there are few, you can manually inspect the regions to decide on an appropriate action.

**Comment by etvedte** [comment]
If you attach your suggested edits (paste in comment box or attach text file) we will review and make needed changes. Thanks!

**Comment by conchoecia** [comment]
@etvedte I've written a script to parse the report file and split the input assembly at the internal trim sites. Would you mind taking a look? https://github.com/conchoecia/genome_assembly_pipelines/blob/master/scripts/NCBI_fcs_adapter_break.py

One of my concerns is that I didn't write the indexing properly converting from the coordinate system you're using to slicing the python strings: [here](https://github.com/conchoecia/genome_assembly_pipelines/blob/1fb29ea60309b4de8497f8b7a4f831af8e2ab397/scripts/NCBI_fcs_adapter_break.py#L71) and [here](https://github.com/conchoecia/genome_assembly_pipelines/blob/1fb29ea60309b4de8497f8b7a4f831af8e2ab397/scripts/NCBI_fcs_adapter_break.py#L112), for example.

**Comment by etvedte** [comment]
There are now instructions to mask vs. split on adaptor matches in the FCS-adaptor wiki.
