### ISSUE TITLE
Making singularity the default engine

### ISSUE THREAD

**Issue by Jokendo-collab** [ncbi/fcs#50]
I am a fellow at NIH. I would like to run fcs on my genome assembly but it appear like the NIH HPC nolonger supports docker. I get the following error when I run fcs. Could you make singularity the default engine?
```
  File "/usr/local/Anaconda/envs/py3.10/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Anaconda/envs/py3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Anaconda/envs/py3.10/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'docker
```

**Comment by pstrope** [comment]
If you have Singularity installed, and do the following, it will use the singularity image. Was there any problem with that?
```
curl https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/FCS/releases/latest/fcs-gx.sif -Lo fcs-gx.sif
export FCS_DEFAULT_IMAGE=fcs-gx.sif
```

**Comment by pstrope** [comment]
OK, please provide the command that failed. Did you run it on biowulf cluster? Thanks.

**Comment by Jokendo-collab** [comment]
Yes

**Comment by Jokendo-collab** [comment]
```
python3 fcs.py screen genome --image fcs-gx.sif --fasta ./fcsgx_test.fa.gz --out-dir ./gx_out/ --gx-db "LOCAL_DB" --tax-id 6973
```

**Comment by pstrope** [comment]
Where did you save the test db? Instead of using "LOCAL_DB" 
use the path to the db like  
/data/jokendo/test-only
(that's an example)

**Comment by Jokendo-collab** [comment]
I have them saved here `/data/okendojo/fcs_gx/test_data`

**Comment by pstrope** [comment]
First confirm that there is a folder `test-only` within `/data/okendojo/fcs_gx/test_data`
Then use `--gx-db /data/okendojo/fcs_gx/test_data/test-only `
in the above command

**Comment by Jokendo-collab** [comment]
my dir tree look as follow:
```
.
├── test-only.blast_div.tsv.gz
├── test-only.gxi
├── test-only.gxs
├── test-only.manifest
├── test-only.meta.jsonl
├── test-only.seq_info.tsv.gz
└── test-only.taxa.tsv

0 directories, 7 files
```
I will delete everything and do another directory setting tomorrow

**Comment by pstrope** [comment]
Let us know how it goes.

**Comment by pstrope** [comment]
closing. please reach out if you still have issues with FCS.
