### ISSUE TITLE
[BUG]: fcs.py fails to download database

### ISSUE THREAD

**Issue by h836472** [ncbi/fcs#51]
*Describe the bug*
fcs.py dies with error when trying to download database

*To Reproduce*
fcs.py db get --mft "$SOURCE_DB_MANIFEST" --dir "$LOCAL_DB/gxdb" 

#
#SOURCE_DB_MANIFEST="https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/FCS/database/latest/all.manifest"
#

If you are having trouble with your genome, please ensure that you can run the pipeline with one of our test genomes first. If your installation works fine with the sample input, please tell us if you are willing and able to share your genome with us, if asked.

*Software versions (please complete the following information):*
 - OS [e.g. CentOS 7, macOS , etc.]. CentOS7
 - Python version if using FCS-GX [``python --version``]. Python 3.6.8

*Log Files*
Please rerun with the ``--debug`` flag and attach an archive (e.g. zip or tarball) of the logs in the directory [``debug/tmp-outdir*.log``] for FCS-adaptor or the saved log file [``run_gx.py ... > GX.log 2>&1``] for FCS-GX.

balintb@node7:/node7_data/balintb/fcs$ python3 fcs.py db get --mft "$SOURCE_DB_MANIFEST" --dir "$LOCAL_DB/gxdb" 
Traceback (most recent call last):
  File "fcs.py", line 480, in <module>
    sys.exit(main())
  File "fcs.py", line 469, in main
    gx.run()
  File "fcs.py", line 386, in run
    self.args.func(self)
  File "fcs.py", line 376, in run_db_mode
    self.run_sync_files()
  File "fcs.py", line 189, in run_sync_files
    self.safe_exec(sync_files_args)
  File "fcs.py", line 150, in safe_exec
    subprocess.run(args, shell=False, check=True, text=True, stdout=sys.stdout, stderr=sys.stderr)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'

*Additional context*

**Comment by pstrope** [comment]
Hi, Could you try with python3.7, and see if it works? 

thanks,
Pooja

**Comment by h836472** [comment]
Dear Pooja,

Thank you for your prompt answer. Yes, the error occurred because of python
version conflict. Then, I tried installing pyenv and then python v3.10.12
on the  centOS 7 compute server but python compilation keeps failing with
some openssl issue. That way, I am now pulling the "all" database with the
python script using my more recent desktop, while sending the files on the
big central storage. Duct-tape with wd40 kind of solution but works...

Thanks again!

Balazs

**Comment by pstrope** [comment]
We'll that's a solution for now. I wonder if you're going to come across problems during the run due to version conflict.

**Comment by h836472** [comment]
Dear Pooja,

Plan is to start the fcs-gx docker image on the compute node with an
interactive console and manually command the analysis engine from the
inside. I can manage mounting host directories for docker and the command
line options of the embedded app also seems to be straightforward. I might
not need the wrapper .py script any longer. Too bad that python interpreter
changes so much between sub-versions and such version conflicts can occur.

Balazs

**Comment by pstrope** [comment]
Closing the ticket. Hope it's working for you.
