### ISSUE TITLE
Can I provide a tax-id at a level higher than species?

### ISSUE THREAD

**Issue by maruiqi0710** [ncbi/fcs#52]
Can I provide a tax-id at a level higher than species? For example, I have assembled a _Saccharomyces cerevisiae_ and this assembly may have horizontal gene transfer from other species within the fungal kingdom. I only want to remove the contamination from bacteria and humans, avoiding removing horizontal gene transfer events within the fungal kingdom. Can I set the tax-id to the fungal (4751) instead of _Saccharomyces cerevisiae_(4932)?

**Comment by etvedte** [comment]
Hello,

We do not currently support setting the tax-id to a higher level to achieve the functionality you describe above. You can technically set the tax-id to 4751, but in this specific example GX sets a generic fungi group as the taxonomic division for differentiating between source vs. contaminant. This could lead to odd results (e.g. the entire genome is called contaminant) although I did test a S. cerevisiae genome with that tax-id this morning and it worked fine. You can also set GX to ignore hits for specific tax-ids (see https://github.com/ncbi/fcs/wiki/FCS-GX#environment-variables), but not higher levels like all fungi.

To address your question, GX will only identify HGT as a "contaminant" if it is from a taxonomically distant group and we have higher stringency requirements in place for reporting chimeric contaminants when the source vs contaminant comparison is within the same taxonomic kingdom. We previously performed testing on a set of bacteria with known HGT and found very few instances of false positive contaminant calls. If you believe GX is reporting verified HGT events as contamination, please report back and we can investigate further.

Eric

**Comment by etvedte** [comment]
Closing. Please let us know if you encounter any additional issues.
