### ISSUE TITLE
Running FCS-GX on genomes of unidentified prokaryotic organisms

### ISSUE THREAD

**Issue by d-golzato** [ncbi/fcs#56]
Dear FCS-GX developers, thank you for this invaluable tool!

I need to submit a prokaryotic genome to NCBI for which no Taxonomy ID is available. However, I want to proactively check for potential contaminating sequences in advance of submission. Currently, I am using the generic Taxonomy ID 2725 (unidentified prokaryotic organism) to run FCS-GX, as I expect it to identify and remove any sequences originating from non-prokaryotic organisms.

I have a few questions on this matter:

- Do you have any recommendations for running FCS-GX on fasta files of unidentified prokaryotic organisms?
- How does NCBI screen for contamination sequences in a genome when a provisional taxonomy ID is utilized?
- Is FCS-GX with its default parameters equivalent to the contamination screening performed by NCBI after genome submission? Should I change any specific parameter to obtain the same results?

I would greatly appreciate your assistance with any of these queries. Thank you.

**Comment by etvedte** [comment]
Hello,

Interesting use case. Is this a metagenome or a genome? 

Tax-id 2725 corresponds to "other unclassified bacteria" and is not a superset of all bacteria. So running with that tax-id in this situation is not the preferred option. 

I would recommend running the genome with the parameter `--species unknown` and not specifying the `--tax-id` parameter to allow GX to make its best guess on the source organism. Next, look at the log for the GX run. There should be one or more prokaryote divisions listed under `Inferred primary-divs      :` . The first division in that list is the prokaryote group that had the largest aggregate coverage to the query genome. You can then re-run the genome with `--species` or `--tax-id` corresponding to that prokaryote group. For example, if a-proteobacteria is the first division, you could run `--species alphaproteobacteria` or `--tax-id 28211`. 

> Is FCS-GX with its default parameters equivalent to the contamination screening performed by NCBI after genome submission? Should I change any specific parameter to obtain the same results?

Use the default FCS-GX parameters. There are some small screens done in internal testing that aren't yet pushed out to external...we will be unifying the two in the future. For now, please also run FCS-adaptor to match NCBI results.

**Comment by d-golzato** [comment]
Hello etvedte,

Thanks for your quick and exhaustive answer!
I'm working with single-amplified genomes of unknown species.  I've tried to run fcs-gx with the `--species unknown` parameter but I'm getting an error due to `--tax-id` being required:

> python ./fcs.py  --image ./fcs-gx.sif screen genome --fasta fcsgx_test.fa.gz --out-dir gx-out --species unknown --gx-db "$GXDB/gxdb/"

> INFO:    Converting SIF file to temporary sandbox...
> usage: screen genome [-h] --fasta FASTA_FILE --tax-id TAX_ID [--species SPECIES] [--split-fasta BOOL] [--div DIV] [--gx-db GX_DB] [--mask-transposons BOOL] [--bin-dir BIN_DIR] [--allow-same-species BOOL] [--out-basename NAME]
>                      [--out-dir OUT_DIR] [--action-report BOOL] [--save-hits BOOL] [--generate-logfile BOOL] [--debug]
> screen genome: error: the following arguments are required: --tax-id
> INFO:    Cleaning up image...

I'm curious whether NCBI's contamination filtering process for unknown species works with the method you suggested to me, i.e  identifying the group with the largest aggregate coverage and then re-running the filtering using that specific tax ID. Or, in the case of unknown species, does NCBI provides a general tax ID for the entire bacterial kingdom (Taxonomy ID: 2) to FCS-GX?

One concern I have about choosing a specific `--tax-id` is that FCS-GX might flag contigs or sequences as contaminants when they are actually a legitimate part of the species genome, just because they exhibit conservation with an already recognized species. Can this be a problem?
