### ISSUE TITLE
FATAL:   could not open image fcs-adaptor.sif: SIF imagefcs-adaptor.sif is corrupted: wrong partition size

### ISSUE THREAD

**Issue by Catherine9826** [ncbi/fcs#57]
After i  curl the sif image, i use the command :./run_fcsadaptor.sh --fasta-input ./inputdir/fcsadaptor_prok_test.fa.gz --output-dir ./outputdir --prok --container-engine singularity --image fcs-adaptor.sif.

But error comes : FATAL:   could not open image fcs-adaptor.sif: SIF imagefcs-adaptor.sif is corrupted: wrong partition size.

**Comment by etvedte** [comment]
Hello,

I assume you curl'd the most recent version of this file, i.e. after March 7? Can you (a) check the file size and/or (b) do a `md5sum` command?
```
md5sum fcs-adaptor.sif 
0bf2d60f14c5a2cf248e26a613b52f07  fcs-adaptor.sif
```

It may be that you had an interrupted/problematic download. Try deleting the file, then re-download

**Comment by Catherine9826** [comment]
Thanks for your help! I curled the wrong version.
