### ISSUE TITLE
[FEATURE REQUEST]: shebang for `fcs.py`

### ISSUE THREAD

**Issue by schellt** [ncbi/fcs#60]
*Is this a feature request for FCS-adaptor or FCS-GX?*
This is a feature request for FCS-GX.

*Describe the problem you'd like to be solved*
After making `fcs.py` executable, running the script directly, instead of `python3 fcs.py` (as in the wiki) causes an error.
It would be more convenient if the shebang would be already present.

*Describe the solution you'd like*
Add `#!/usr/bin/env python3` as the first line in `fcs.py`.

*Describe alternatives you've considered*
No alternatives considered.

**Comment by etvedte** [comment]
Hello,

We will plan to add this in a future patch or release. Since we just released v.0.5.0, I don't anticipate this being added in the immediate future. Please continue to use `python3 fcs.py` for now. 

Eric

**Comment by etvedte** [comment]
This has been added for v0.5.4
https://github.com/ncbi/fcs/raw/main/dist/fcs.py
