### ISSUE TITLE
[FEATURE REQUEST]: Support on FASTQ/FASTQ.gz as an input and output

### ISSUE THREAD

**Issue by mingyanisa** [ncbi/fcs#64]
*Is this a feature request for FCS-adaptor or FCS-GX?*
Both 

*Describe the problem you'd like to be solved*

I am inquiring about an additional option to support fastq.gz files as input and as output for both tools. Currently, the tools do not support fastq.gz files as input. I would like to understand if there are plans to incorporate this feature in the future.

Additionally, I am curious about how downstream tools are expected to handle the quality scores for alignment when using the resulting FASTA files from this tool. Could you give me some guidance or best practices for making sure that quality scores are appropriately handled in the downstream process?

Last question, the tools give the fasta file (.fasta) as an output at the moment. Is it possible to get the end result in fasta.gz format? Or do we need to run gzip to the output FASTA file by ourselves? What is the best practice for this step?

Thank you for your attention to this matter.

*Describe the solution you'd like*
Both tools could accept the FastQ file as input, resulting in the output file as either FASTQ or FASTQ.gz.

*Describe alternatives you've considered*
NA

**Comment by etvedte** [comment]
See the response to Issue #58. Points to re-iterate:

- We haven't done testing of FCS tools on reads and do not currently plan to support FASTQ input. FCS-GX in particular has logic design choices with assembly-based screening in mind and may produce unexpected results for reads. 
- If you _do_ want to experiment on reads, I would suggest converting to FASTA, run FCS, then use seqkit to subset your FASTQ for sequences of interest. 

> Last question, the tools give the fasta file (.fasta) as an output at the moment. Is it possible to get the end result in fasta.gz format? Or do we need to run gzip to the output FASTA file by ourselves? What is the best practice for this step?

Yes right now you have to gzip yourself. We can consider adding support for output as fasta.gz
