### ISSUE TITLE
[BUG]: <title>subprocess.CalledProcessError

### ISSUE THREAD

**Issue by zhaoxuetong** [ncbi/fcs#77]
I am non-cloud users, using the 'all' db.
Caching the database:
$free -mh
              total        used        free      shared  buff/cache   available
Mem:           1.0T        168G         17G        463G        822G        375G
Swap:           18G         18G         20K

python3 ./fcs.py --env-file env.txt screen genome --fasta ./T2T-CHM13v2.0_genomic.fna --out-dir ./gx_out_T2T_4/ --gx-db "/my_tmpfs/gxdb" --tax-id 9606 --generate-logfile T

Traceback (most recent call last):
  File "./fcs.py", line 445, in <module>
    sys.exit(main())
  File "./fcs.py", line 434, in main
    gx.run()
  File "./fcs.py", line 345, in run
    self.args.func(self)
  File "./fcs.py", line 323, in run_screen_mode
    self.run_gx()
  File "./fcs.py", line 241, in run_gx
    self.safe_exec(docker_args)
  File "./fcs.py", line 166, in safe_exec
    subprocess.run(args, shell=False, check=True, stdout=sys.stdout, stderr=sys.stderr)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'run', '--env-file', 'env.txt', '-i', '--rm', '-v', '/my_tmpfs:/app/db/gxdb/', '-v', '/xtdisk/baoym_group/jiayk/zhaoxt:/sample-volume/', '-v', '/xtdisk/baoym_group/jiayk/zhaoxt/gx_out_T2T_4:/output-volume/', 'ncbi/fcs-gx:latest', 'python3', '/app/bin/run_gx', '--fasta', '/sample-volume/T2T-CHM13v2.0_genomic.fna', '--out-dir', '/output-volume/', '--gx-db', '/app/db/gxdb/gxdb', '--tax-id', '9606', '--generate-logfile', 'T']' returned non-zero exit status 129.

**Comment by etvedte** [comment]
Hello,

Can you run in debug mode i.e. `python3 ./fcs.py screen genome --debug ...` and attach a file with the log output?

FYI, if you are interested in looking for contamination reports for genomes hosted on NCBI, we have results posted for runs conducted in April 2023 at https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/FCS/reports/current/. There are a files for GenBank, GenBank prokaryote multiisolate, and RefSeq. You can search the file for the accession of interest like so:
```
zcat gx_summary_genbank.20230416.tsv.gz
GCA_009914755.4 GenBank GCF_009914755.1 Y       T2T-CHM13v2.0   9606    9606    Homo sapiens                    PRI     PRJNA559484             na      Complete Genome Jan 24 2022 01:18:00:000PM      Jan 26 2022 09:09:47:090AM          T2T Consortium           3117292070      3117292070      25      N       Mar 21 2023 01:03:19:000PM      anml:primates   anml:primates   0.93370 0       0       0.00000 0       0       0       0       0       0       0       0       0   00       0       0       0       -       -

zcat gx_details_genbank.20230416.tsv.gz | grep GCA_009914755.4
<empty>
```
The presence of GCA_009914755.4 in the gx_summary* file means that this genome was screened as part of the large batch run in April 2023. The absence of any rows in the gx_details* file means there was no contamination identified by GX in this genome.

**Comment by zhaoxuetong** [comment]
Thank you for your patient response!
I have solved the above problem because my server crashed after running for 15 minutes. Then I tested it again and it took 40 minutes to run. How can we shorten the time? I read in the article (Astashyn et al. Genome Biology) that FCS-GX screens most genomes in 0.1–10 min.
I am non-cloud users, using the 'all' db.
Caching the database:

$free -mh
total used free shared buff/cache available
Mem: 1.0T 168G 17G 463G 822G 375G
Swap: 18G 18G 20K

$cat env.txt
GX_NUM_CORES=8

python3 ./fcs.py --env-file env.txt screen genome --fasta ./T2T-CHM13v2.0_genomic.fna --out-dir ./gx_out_T2T_6/ --gx-db "/my_tmpfs/gxdb" --tax-id 9606 --generate-logfile T --debug


Thanks for your help.

**Comment by etvedte** [comment]
Couple of questions:

1. I'm assuming here you followed the instructions for caching the db, i.e. you have sudo permissions and mounted the db on a tmpfs- or ramfs-backed filesystem. Simply making a space on disk called `my_tmpfs`, downloading the db there, and running without mounting will slow GX runtime. 

2. How many cores does your host have? If you don't set `--env-file` then GX by default will use 48 cores or the maximum amount available, whichever is less.

**Comment by etvedte** [comment]
Closing. Please reopen if you need to discuss further.
