### ISSUE TITLE
Change default container path

### ISSUE THREAD

**Issue by weilu1998** [ncbi/fcs#8]
Hi,

I was trying to run FCS-GX on a server (login node) and encountered this error. I am wondering is there a way to change the default container building path?

`container creation failed: mount /scratch/local->/scratch/local error:
while mounting /scratch/local: mount source /scratch/local doesn't exist`

Thanks,
Wei

**Comment by deaconjs** [comment]
Hi Wei, 

the FCS-GX wiki does not mention use of /scratch. Are you trying to put a local backup copy in your scratch folder ie with --gx-db-disk? How are you deviating from the walkthrough exactly?

Thanks!

**Comment by weilu1998** [comment]
Hi @deaconjs ,

Thanks for the reply! No, I was just following the FCS-GX wiki page and encountered this error at step 7. I was running the script on a cluster. I think the path "/scratch/local" was written inside the sif file. For example, when I run the following command (not passing any variable), I still encounter this error.

`singularity exec --cleanenv fcsgx.sif env`

INFO:    Converting SIF file to temporary sandbox...
WARNING: skipping mount of /scratch/local: stat /scratch/local: no such file or directory
INFO:    Cleaning up image...
FATAL:   container creation failed: mount /scratch/local->/scratch/local error: while mounting /scratch/local: mount source /scratch/local doesn't exist

**Comment by weilu1998** [comment]
Hi @deaconjs ,

Thanks for the reply! Sorry, I previously thought the path "/scratch/local" was written inside the sif image because I will get the error even when I don't input any variable. Later on, I tried a different version of singularity and the problem was solved.

Thanks,
Wei

**Comment by deaconjs** [comment]
Thanks for getting back to us Wei. Glad things are working out for you!

Deacon
