### ISSUE TITLE
Problems with downloading all.gxi and all.gxs files

### ISSUE THREAD

**Issue by qb-lyu** [ncbi/fcs#85]
I found that downloading the database via sync_files.py was very slow, especially for all.gxi and all.gxs files. How do I download this data through Aspera? This will greatly improve download speed. 

I can find FCS directory in the address (https://www.ncbi.nlm.nih.gov/public/), but there's no "database" in the directory. However, I can through the browser to the address https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/FCS/database/latest/

**Comment by etvedte** [comment]
Can you try this:
`ascp -QT -l1g -i <key> anonftp@ftp.ncbi.nlm.nih.gov:/genomes/TOOLS/FCS/database/latest/all.gxi /path/to/local/all.gxi`

You might want to change the transfer rate if needed

**Comment by etvedte** [comment]
Please re-open this issue if you have additional questions.
