### ISSUE TITLE
Issue with using get-fasta command

### ISSUE THREAD

**Issue by ShenMJ99** [ncbi/fcs#87]
I found the README on https://github.com/ncbi/fcs-gx/tree/release which mentions Useful GX subcommands. I am interested in using the get-fasta functionality described there. However, I noticed that the path ./dist/gx, which is supposed to point to ../build/src/gx, does not exist.

The README describes the functionality as follows:

"The sequences used to build the gx database are listed in the file all.seq_info.tsv.gz within the gxdb folder. From there, you can select the sequences of your choice, and then generate the fasta files using the gx get-fasta subcommand:
./dist/gx get-fasta --db /dev/shm/gxdb/all.gxi --input 3col.txt --output out.txt
The input file, which is provided by the user, is a tab delimited, 3 column file in the following format, along with the header:

cat 3col.txt
##[["GX locs",1,1]]
NC_060925.1 . .
To get the fasta for a specific set of coordinates, format your input file with the start and end coordinates in the 2nd and 3rd column, respectively:

##[["GX locs",1,1]]
NC_060925.1 1 200"

Could you please provide guidance on how to implement this sub-functionality, considering the discrepancy in the path and how to correctly use the get-fasta command?

**Comment by etvedte** [comment]
The path should already exist when you `git clone` the repo.  But prior to executing any GX commands, be sure to build with `make` first. otherwise it won't work. My guess is that you forgot to do that.

```
git clone https://github.com/ncbi/fcs-gx.git
cd fcs-gx

ls -l dist/gx
lrwxrwxrwx 1 tvedtees giindex 15 Jun 17 08:50 dist/gx -> ../build/src/gx

./dist/gx get-fasta --help
bash: ./dist/gx: No such file or directory

make
...
...
[100%] Built target gx

./dist/gx get-fasta --help
Fetch fasta from db.
Usage: ./dist/gx get-fasta [OPTIONS]

Options:
  -i,--input file [stdin]     3-column TSV of locs, same format as --hardmask in make-db mode.
                              
                              
  --gx-db file [db/all.gxi]   /dev/shm/path/to/gxdb/ produced by gx make-db.
                              Should be placed in RAM-disk.
                              
  -o,--output file [stdout]   Fasta.
                              
  -h,--help                   Print this help message and exit.

```
Eric

**Comment by etvedte** [comment]
Please re-open this issue if you have additional questions.
