### ISSUE TITLE
Request for Conda Installation Option for fcs-gx on GitHub

### ISSUE THREAD

**Issue by wangshuangyi** [ncbi/fcs#92]
Hello,

I've recently been using your software, fcs-gx, on GitHub for genome sequence decontamination. However, I've encountered difficulties as the current setup requires either Docker or Singularity, and I lack root permissions to use them effectively. I'd like to suggest adding a Conda installation option for users like me who face these limitations. This would make your software more accessible and easier to use in environments where Docker or Singularity setups are challenging.

Thank you for considering this enhancement!

Best regards,
Shuangyi Wang

**Comment by etvedte** [comment]
GX is available as a conda recipe [here](https://bioconda.github.io/recipes/ncbi-fcs-gx/README.html#package-package%20&#x27;ncbi-fcs-gx&#x27;).

We don't provide documentation on how to use the conda install, but note:

1. The conda install currently only supports local use of GX, not FCS-adaptor
2. The [source code repo](https://github.com/ncbi/fcs-gx) for fcs-gx and Issue #74 will help
