### ISSUE TITLE
Understanding clean.fasta and contam.fasta

### ISSUE THREAD

**Issue by katiecdillon** [ncbi/fcs#99]
I ran FCS-GX on my tick genome, but would like a clearer explanation of the "Separated cleaned and contaminated sequences" portion of the wiki. It is still not clear to me what is being extracted from the assembly and placed into contam.fasta. I have some collaborators that use the output as instructions to go back to the original input assembly and use bedtools to TRIM, FIX, and/or EXCLUDE said sequences. But aren't all of those actions already been taken by FCS-GX, hence the reason for the clean.fasta and contam.fasta? Or am I naive and there are user-specific actions that need to be made to achieve a contaminant-free assembly?

**Comment by etvedte** [comment]
Hello,

`fcs.py screen genome` produces the file `*.fcs_gx_report.txt` which represents the final contamination report containing suggested cleaning actions. Those cleaning actions can be completed using `fcs.py clean genome` by supplying the original FASTA with the FCS-GX report. `fcs.py clean genome` will produce a log summary of the cleaning actions taken, something like:

```
Applied 405 actions; 402417 bps dropped; 1922 bps hardmasked. 
```

So if you/the collaborators use `fcs.py clean genome`, there is no need to do an additional `bedtools` command to get a contaminant-free assembly. 

The "Separated cleaned and contaminated sequences" section of the wiki does have some differences with the current behavior of `fcs.py clean genome`, but it is limited to what is placed in `contam.fa`. Namely, currently only sequences assigned as entirely contaminant, i.e. `EXCLUDE`, are populated in `contam.fa`. Partial spans on contig ends `TRIM` or internal spans `FIX` are removed from `clean.fa` but not populated in `contam.fa`. For most users this isn't an issue, with the end goal being to retain the final set of cleaned sequences. But if you want to retain contaminant `TRIM` / `FIX` spans you will need to use something like `bedtools`.

Eric

**Comment by katiecdillon** [comment]
Hello Eric thank you so much, this makes a lot more sense now. Thank you!!
